spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://config-service:8088"

---

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8088"